# Don't forget to restart your server if this file is modified

default: &default
  # Primary Database
  db_host: <%= ENV["DB_HOST"] %>
  db_name: <%= ENV["DB_NAME"] %>
  db_username: <%= ENV["DB_USERNAME"] %>
  db_password: <%= ENV["DB_PASSWORD"] %>
  db_pool: <%= ENV["DB_POOL"] || 30 %>
  rapidapi_base_url: <%= ENV["RAPIDAPI_BASE_URL"] %>
  rapidapi_key: <%= ENV["RAPIDAPI_KEY"] %>
  rapidapi_host: <%= ENV["RAPIDAPI_HOST"] %>
  authentication_system: <%= ENV["AUTHENTICATION_SYSTEM"] %>


development:
  <<: *default
  # Database
  db_host: <%= ENV["DB_HOST"] || "127.0.0.1" %>
  db_name: <%= ENV["DB_NAME"] || "" %>
  db_username: <%= ENV["DB_USERNAME"] || "root" %>
  db_password: <%= ENV["DB_PASSWORD"] || "root" %>

test:
  <<: *default
  db_host: <%= ENV["TEST_DB_HOST"] || "127.0.0.1" %>
  db_username: <%= ENV["TEST_DB_USERNAME"] || "root" %>
  db_password: <%= ENV["TEST_DB_PASSWORD"] || "root" %>

production:
  <<: *default
